"""Report rendering, markdown and self-contained HTML.

The HTML embeds the figure as a base64 data URI and all CSS inline, so
one file can be emailed or attached to a lab notebook. Output is plain
ASCII, angle brackets and ampersands in data values are escaped with
HTML entities.
"""

import base64
import datetime

from .checks import format_num, format_p

FOOTER_TEXT = ("Generated by statsage, a free tool by Paul Crinigan, AI Apps API. "
               "More free science tools at learnhowtoscience.com.")

CSS = """
body { font-family: Arial, Helvetica, sans-serif; color: #1a1a1a; margin: 0;
       background: #f4f5f7; }
.page { max-width: 820px; margin: 24px auto; background: #ffffff; padding: 36px 44px;
        border: 1px solid #d9dce1; border-radius: 6px; }
h1 { font-size: 22px; margin: 0 0 4px 0; }
h2 { font-size: 16px; margin: 26px 0 8px 0; border-bottom: 1px solid #e3e5e9;
     padding-bottom: 4px; }
.sub { color: #6a7078; font-size: 13px; margin-bottom: 18px; }
table { border-collapse: collapse; width: 100%; font-size: 14px; margin: 8px 0; }
th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #e9ebee; }
th { background: #f7f8fa; font-weight: 600; }
.pass { color: #1a7f37; font-weight: 600; }
.fail { color: #b42318; font-weight: 600; }
.note { color: #8a6d1d; font-weight: 600; }
.big { font-size: 17px; font-weight: 700; }
.warn { background: #fff8e6; border: 1px solid #f0dfa8; border-radius: 4px;
        padding: 10px 14px; font-size: 14px; margin: 8px 0; }
.copy { background: #f7f8fa; border: 1px solid #e3e5e9; border-radius: 4px;
        padding: 12px 16px; font-size: 14px; line-height: 1.55; }
.trace li { margin-bottom: 4px; }
img.figure { max-width: 100%; height: auto; border: 1px solid #e3e5e9;
             border-radius: 4px; margin-top: 6px; }
.footer { margin-top: 30px; padding-top: 12px; border-top: 1px solid #e3e5e9;
          font-size: 12px; color: #6a7078; }
.footer a { color: #0b62a4; }
"""


def esc(text):
    return (str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _status(passed):
    if passed is True:
        return '<span class="pass">pass</span>', "pass"
    if passed is False:
        return '<span class="fail">fail</span>', "fail"
    return '<span class="note">note</span>', "note"


def build_markdown(result):
    r = result
    lines = ["# statsage report", ""]
    lines.append("Analysis: " + r.test["name"] + "  ")
    lines.append("Generated: " + r.generated + "  ")
    lines.append("")
    lines.append("## Result")
    lines.append("")
    lines.append(_headline(r))
    lines.append("")
    lines.append("## Descriptives")
    lines.append("")
    lines.append("| group | n | mean | SD | median |")
    lines.append("|---|---|---|---|---|")
    for d in r.test["descriptives"]:
        lines.append("| " + str(d["group"]) + " | " + str(d["n"]) + " | "
                     + format_num(d["mean"]) + " | " + format_num(d["sd"])
                     + " | " + format_num(d["median"]) + " |")
    lines.append("")
    lines.append("## Assumption checks")
    lines.append("")
    for c in r.checks:
        _, word = _status(c["passed"])
        lines.append("- [" + word + "] " + c["name"] + ": " + c["detail"])
    lines.append("")
    lines.append("## Why this test")
    lines.append("")
    for step in r.trace:
        lines.append("- " + step)
    if r.test["posthoc"]:
        lines.append("")
        lines.append("## Post-hoc comparisons (" + r.test["posthoc"][0]["method"] + ")")
        lines.append("")
        lines.append("| pair | p |")
        lines.append("|---|---|")
        for ph in r.test["posthoc"]:
            lines.append("| " + ph["pair"] + " | " + format_p(ph["p"]) + " |")
    if r.warnings:
        lines.append("")
        lines.append("## Warnings")
        lines.append("")
        for w in r.warnings:
            lines.append("- " + w)
    lines.append("")
    lines.append("## Methods paragraph (copy-paste)")
    lines.append("")
    lines.append(r.methods_text)
    lines.append("")
    lines.append("## Results sentence (copy-paste)")
    lines.append("")
    lines.append(r.results_text)
    lines.append("")
    lines.append("---")
    lines.append(FOOTER_TEXT)
    return "\n".join(lines)


def _headline(r):
    p = r.test["p"]
    sig = "significant" if p < r.alpha else "not significant"
    p_text = "p < 0.001" if p < 0.001 else "p = " + format_p(p)
    text = (r.test["name"] + ": " + p_text + " (" + sig
            + " at alpha = " + str(r.alpha) + ")")
    effect = r.test.get("effect")
    if effect and effect.get("value") is not None:
        text += ", " + effect["interpretation"]
    ci = r.test.get("ci")
    if ci:
        text += ", " + ci["label"] + " " + format_num(ci["low"]) + " to " + format_num(ci["high"])
    return text + "."


def build_html(result):
    r = result
    parts = ['<div class="page">']
    parts.append("<h1>statsage report</h1>")
    parts.append('<div class="sub">' + esc(r.test["name"]) + " &middot; generated "
                 + esc(r.generated) + "</div>")

    parts.append("<h2>Result</h2>")
    parts.append('<p class="big">' + esc(_headline(r)) + "</p>")
    if r.figure_png:
        b64 = base64.b64encode(r.figure_png).decode("ascii")
        parts.append('<img class="figure" alt="statsage figure" src="data:image/png;base64,'
                     + b64 + '">')

    parts.append("<h2>Descriptives</h2>")
    parts.append("<table><tr><th>group</th><th>n</th><th>mean</th><th>SD</th><th>median</th></tr>")
    for d in r.test["descriptives"]:
        parts.append("<tr><td>" + esc(d["group"]) + "</td><td>" + str(d["n"]) + "</td><td>"
                     + format_num(d["mean"]) + "</td><td>" + format_num(d["sd"])
                     + "</td><td>" + format_num(d["median"]) + "</td></tr>")
    parts.append("</table>")

    parts.append("<h2>Assumption checks</h2>")
    parts.append("<table><tr><th>check</th><th>status</th><th>detail</th></tr>")
    for c in r.checks:
        badge, _ = _status(c["passed"])
        parts.append("<tr><td>" + esc(c["name"]) + "</td><td>" + badge + "</td><td>"
                     + esc(c["detail"]) + "</td></tr>")
    parts.append("</table>")

    parts.append("<h2>Why this test</h2>")
    parts.append('<ol class="trace">')
    for step in r.trace:
        parts.append("<li>" + esc(step) + "</li>")
    parts.append("</ol>")

    if r.test["posthoc"]:
        parts.append("<h2>Post-hoc comparisons (" + esc(r.test["posthoc"][0]["method"]) + ")</h2>")
        parts.append("<table><tr><th>pair</th><th>p</th></tr>")
        for ph in r.test["posthoc"]:
            style = ' class="pass"' if ph["p"] < r.alpha else ""
            parts.append("<tr><td>" + esc(ph["pair"]) + "</td><td" + style + ">"
                         + format_p(ph["p"]) + "</td></tr>")
        parts.append("</table>")

    if r.warnings:
        parts.append("<h2>Warnings</h2>")
        for w in r.warnings:
            parts.append('<div class="warn">' + esc(w) + "</div>")

    parts.append("<h2>Methods paragraph (copy-paste)</h2>")
    parts.append('<div class="copy">' + esc(r.methods_text) + "</div>")
    parts.append("<h2>Results sentence (copy-paste)</h2>")
    parts.append('<div class="copy">' + esc(r.results_text) + "</div>")

    parts.append('<div class="footer">Generated by <strong>statsage</strong>, a free tool by '
                 '<a href="https://www.aiappsapi.com">Paul Crinigan, AI Apps API</a>. '
                 'More free science tools at '
                 '<a href="https://www.learnhowtoscience.com">learnhowtoscience.com</a>.</div>')
    parts.append("</div>")

    return ("<!DOCTYPE html><html><head><meta charset=\"utf-8\">"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            "<title>statsage report</title><style>" + CSS + "</style></head><body>"
            + "\n".join(parts) + "</body></html>")


def timestamp():
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
